name:                hw1
version:             0.1.0.0
github:              "githubuser/hw1"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hw1#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  hw1-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw1

tests:
  hw1-t1-test:
    main:                Spec.hs
    source-dirs:         test/T1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw1
    - tasty-hspec
    - tasty-hedgehog
    - tasty
    - hspec
    - hedgehog
    - containers
  hw1-t2-test:
    main:                Spec.hs
    source-dirs:         test/T2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw1
    - tasty-hspec
    - tasty-hedgehog
    - tasty
    - hspec
    - hedgehog
    - containers
  hw1-t34-test:
    main:                Spec.hs
    source-dirs:         test/T3T4
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw1
    - tasty-hspec
    - tasty-hedgehog
    - tasty
    - hspec
    - hedgehog
    - containers
  hw1-t5-test:
    main:                Spec.hs
    source-dirs:         test/T5
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw1
    - tasty-hspec
    - tasty-hedgehog
    - tasty
    - hspec
    - hedgehog
    - containers
  hw1-t6-test:
    main:                Spec.hs
    source-dirs:         test/T6
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw1
    - tasty-hspec
    - tasty-hedgehog
    - tasty
    - hspec
    - hedgehog
    - containers
  hw1-t7-test:
    main:                Spec.hs
    source-dirs:         test/T7
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw1
    - tasty-hspec
    - tasty-hedgehog
    - tasty
    - hspec
    - hedgehog
    - containers